apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: Ym9vay1yZHMuY3JneXVzNHc2Y29pLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQo=
  db_username: YWRtaW4K
  db_password: c3JpdmFyZGgK

